export const DEFAULT_KEEP_COLUMNS = [
  'CÓDIGO',
  'PEÇA DESCRIÇÃO',
  'ALTURA (X)',
  'PROF (Y)',
  'ESPESSURA',
  'DESENHO',
  'IDPONTTA'
];

export const DEFAULT_GROUP_COLUMNS = [
  'AMBIENTE',
  'CÓDIGO MATERIAL'
];

export const EDGE_COLUMNS = [
  'BORDA FACE TRASEIRA ESPESSURA-COR',
  'BORDA FACE FRENTE ESPESSURA-COR',
  'BORDA FACE LE ESPESSURA-COR',
  'BORDA FCE LD ESPESSURA-COR'
];
