export const DEFAULT_KEEP_COLUMNS = [
  'CÓDIGO',
  'PEÇA DESCRIÇÃO',
  'ALTURA (X)',
  'PROF (Y)',
  'ESPESSURA',
  'DESENHO',
  'IDPONTTA'
];

export const DEFAULT_GROUP_COLUMNS = [
  'AMBIENTE',
  'CÓDIGO MATERIAL'
];

export const EDGEBANDER45_DESCRIPTION_VALUES = [
  'PUXADOR_45'
];

export const SECTIONING_DESCRIPTION_VALUES = [
  'SEC'
];

export const MACHINING_DESCRIPTION_VALUES = [
  'USI'
];

export const GLUE_DESCRIPTION_VALUES = [
  
];

export const EDGE_COLUMNS = [
  'BORDA FACE TRASEIRA ESPESSURA-COR',
  'BORDA FACE FRENTE ESPESSURA-COR',
  'BORDA FACE LE ESPESSURA-COR',
  'BORDA FCE LD ESPESSURA-COR'
];

export const GLUE_EDGE_VALUES = [
  'COLAR'
];

export const MACHINING_EDGE_VALUES = [
  '4023',
  '4030',
  'RM416',
  'RM_416'
];

export const APP_VERSION = '1.4.2';